Traceback (most recent call last):
  File "/Users/edhall113/opt/anaconda3/envs/JBook/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/edhall113/opt/anaconda3/envs/JBook/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edhall113/opt/anaconda3/envs/JBook/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edhall113/opt/anaconda3/envs/JBook/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/edhall113/opt/anaconda3/envs/JBook/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/edhall113/opt/anaconda3/envs/JBook/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/edhall113/opt/anaconda3/envs/JBook/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
n = 1000
uniform_data = runif(n,0,1)
sample_size = 10

number_samples = 10000

sample_means = c()
for (k in 1:number_samples){
  sample_data = sample(uniform_data,sample_size,replace=TRUE)
  sample_means = c(sample_means,mean(sample_data))
}

mu = 0.5
standard_dev = sqrt(1.0/12.0)

scaled_data = (sample_means-mu)/(standard_dev/sqrt(sample_size))

hist(scaled_data,breaks=20,freq=FALSE,
     xlab="Z",ylab="Relative Frequency",ylim=c(0,0.5),xlim=c(-4,4),
     main="Sample Means of Uniform Dist")

x = seq(-4,4,0.01)
y = dnorm(x)

lines(x,y)
``` -->




------------------


Error in parse(text = x, srcfile = src): attempt to use zero-length variable name
Traceback:


